telegram:
  subscribers_file_name: "./subscribers.json"
  sleeping_time: "10"

  messages:
    successful: "âœ… Connection online for "
    unsuccessful: "ğŸ†˜ Connection offline for "
    subscribed: "ğŸ’š Subscribed ğŸ’š"
    unsubscribed: "ğŸ¤ Unsubscribed ğŸ¤"

  api_id: ""
  api_hash: ""
  phone: ""
  username: ""
  bot_token: ""
  password: ""

  trusted:
    - "YOUR ID"
ssh:
  hostnames:
  - something:
      address: ""
      listener: "default"
  - something2:
      address: ""
      listener: "default"
  username: ""
  pkey_path: ""
